
CREATE TABLE pessoa
(
    id_pessoa           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome         VARCHAR(255)                             NOT NULL,
    departamento VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_pessoa PRIMARY KEY (id_pessoa)
);

CREATE TABLE tarefa
(
    id_tarefa    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo       VARCHAR(255)                             NOT NULL,
    descricao    VARCHAR(255)                             NOT NULL,
    prazo        TIMESTAMP                                NOT NULL,
    departamento VARCHAR(255)                             NOT NULL,
    duracao      INT                                      NOT NULL,
    data_alocacao TIMESTAMP,
    data_finalizacao   TIMESTAMP,
    id_pessoa      INTEGER,
    CONSTRAINT pk_tarefa PRIMARY KEY (id_tarefa),
    CONSTRAINT FK_TAREFA_ON_ID_USER FOREIGN KEY (id_pessoa) REFERENCES pessoa (id_pessoa)
);
